



ALTER TABLE `orders`
	CHANGE COLUMN `order_id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `users`
	CHANGE COLUMN `user_id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `orders`
	CHANGE COLUMN `status` `status` ENUM('ACTIVE','CANCELED','NOTIFIED','EXECUTING','EXECUTED','EXPIRED','FAILED') NOT NULL DEFAULT 'ACTIVE' AFTER `user_id`;

ALTER TABLE `logs`
	CHANGE COLUMN `log_id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `token_errors`
	CHANGE COLUMN `token_error_id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `values`
	ADD COLUMN `id` INT NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (`id`);
